### ISSUE TITLE
Add support for Connect Aktor

### ISSUE THREAD

**Issue by christofkac** [Pix---/ioBroker.homepilot#18]
Hi,
it would be great if support for the connect aktor could be added.
Without this support, the shutter level is displayed in the temperature state with an odd scaling.
See [https://forum.iobroker.net/topic/25227/homepilot-fehler-bei-connect-aktor-kein-level](url) for details.
Thanks!

**Comment by Pix---** [comment]
Hi,
initially I developed this adapter for Rademacher shutter belt actors. From time to time other user contributed data and time to add more actors. As I still only use shutter belt actors I can not really develop further versions. But if you have pull requests I'd really appreciate it.

**Comment by christofkac** [comment]
Hi,
after some search I have found the problem (I think). At the beginning I did not understand why my Aktor with the code 49 behaves differently than the Connect Aktor with the code 4B.
After some checking I realized, that the following code in main.js has a bug:
parseInt(duoferncode.substring(0,2)) < 20 is true for the input '4B' as in that case, parseInt results in '4' as partInt expects a decimal value as parameter.

As the code is in hexadecimal I expect that all lines containing that code have to be changes as following:
parseInt(duoferncode.substring(0,2), 16) < 26
26 instead of 20 as 0x19 is 25.

I know the solution but I don't know how to build that adapter.
Could you please create a new adapter version and I can test it with my configuration?
Thanks
Christof

**Comment by christofkac** [comment]
Hi,
finally I realized that I can simply change the code in my local installation and try it out.
This was successfull, so that I created a pull request with my changes.
I hope those are acceptable.
Thanks for the great adapter!
Bye
Christof
