### ISSUE TITLE
Z-Wave Heizkörperthermostate

### ISSUE THREAD

**Issue by mikepa1** [Pix---/ioBroker.homepilot#3]
Z-Wave Heizkörperthermostate are listed with the homepilot adapter as
"HeizkörperstellantrieZ-Wave" ...
The device level shows the temperature in 0.1°C, so 220 will be shown for 22°C instead of 22!
In the attached Screenshot a temperature of 9.5°C is set shown as 95%.
![image](https://user-images.githubusercontent.com/30804092/29034005-1a6a1754-7b97-11e7-8108-8d5721ef374b.png)

**Comment by Pix---** [comment]
Hello Mikepa1,

thank your for sharing this issue. Please send me the JSON file you get after sending http://homepilot.local/deviceajax.do?devices=1

**Comment by mikepa1** [comment]
Thanks for

 your immediate response, here is the requestetd file:
[Homepilot.zip](https://github.com/Pix---/ioBroker.homepilot/files/1208474/Homepilot.zip)

**Comment by Pix---** [comment]
Hello,

the serial fpr this device seems to be "4". I can opt out the "treat as a level device" fpr this serial. Should be no problem. Unfortunately that won't happen before next week.

**Comment by mikepa1** [comment]
Hello,
Thank you very much for your answer. I'm just starting with iobroker - no time pressure. You did a great job  as all the others did working on iobroker. Thanx for this and have a good time!
Michael

**Comment by Pix---** [comment]
Hello,
you can try 0.2.7 now. It creates a new Datapoint ".temperature". Probably the control temperature function is not working correctly yet.
I am really looking forward to reading your feedback.
Pix

**Comment by mikepa1** [comment]
Hello,
i installed version 0.2.7, but got no connection to homepilot 2. I downgraded to version 0.2.6 again and could connect to the homepilot.
Best regards
Michael

**Comment by Pix---** [comment]
Hello,
thanks for the feedback. I have issues to find the problem as I don't have a ZWAVE device. Do you read any error logs?
Pix

**Comment by mikepa1** [comment]
Hello,
i changed the file main.js and attached it to this mail.. Now it reads the temperature from homepilot correctly and also change is possible.
I limited values to 0..28°C 'cause 28°C is the max. value, the z-wave thermostat can be set to.
Please have a look at my changes because i'm not a javascript expert.

Michael
[main.zip](https://github.com/Pix---/ioBroker.homepilot/files/1264332/main.zip)

**Comment by Pix---** [comment]
Hello Michael,
many thanks for your contribution. I have used your corrections in version 0.2.8. :thumbsup:

Just one more question:
why did you erase the lines which defined the role (temperature) of the new datapoint  (line 228 in main.js)?
`
case "4": // Heizkörperstellantrieb Z-Wave
                devicerole = 'level.temperature';
                break;
`

Pix

**Comment by mikepa1** [comment]
Hello Pix,
first to your question:  the only reason is - i copied it from the "Rohrmotor-Aktor". But i found out another bigger. I added more Z-Wave Heizkörperstellantriebe
and i found that each new device got a new duofern code, the first one started with 4, the next with 5 and then 6. (i have actually 3 devices running).
I could not find out, how many Z-Wave devices are supported by the Homepilot. So i changed the software again to support up to 16 Z-Wave devices and i also
changed the devicerole to level.temperature. I attached the code actually running in my installation.

Michael
[main.zip](https://github.com/Pix---/ioBroker.homepilot/files/1388076/main.zip)

**Comment by Pix---** [comment]
Thank you for updating. I really appreciate.
To suggest new code you can fork the adapters main.js, change it and then make a pull request. Then I can see the changes. It is much more convenient than sending zip-files. 
A new version is online.

**Comment by clmuelle001** [comment]
Hello! Just an annotation to Rademacher and z-Wave. Maybe interesting for you / maybe not: 

I've noticed that Rademacher don't offer z-Wave anymore. They've now their own Duofern-Technology also for Heizkörperstellantriebe and Fensterkontakte. I'm writing this because I saw the roadmap infos for this project mentioned live data for z-wave at version 2.xxx

I got the new Duoferns up and running and already see them in iobroker.

**Comment by Pix---** [comment]
Thank you for this update. 
Do you really see live data from your Duoferns in ioBroker or are you using the homepilot Adapter with 12s-update (default value).

**Comment by clmuelle001** [comment]
...my assumption was that 12 s sync is live data ;-) 

Unfortunately it looks that the Thermostat-Duoferns doesn't work well with yahka and iobroker.homepilot. I just playing around a little bit more to get some more details and to understand what to do.

**Comment by clmuelle001** [comment]
Hi! Your adapter works well. Great job! Thank you! 

I can see 215% when changing the target temprature to 21,5 °C. Now I've to figure out which variables to map in yahka to be able to use the homekit app.
